### ISSUE TITLE
Possible mismatch in terms

### ISSUE THREAD

**Issue by knightpfhor** [disclose/disclose#10]
The core terms include the following item:

- Keep the details of any discovered vulnerabilities confidential until they are fixed, according to the Disclosure Terms in this policy;

My reading of this is that it is referring to whether this is coordinated, discretionary or non-disclosure as defined in variable.md.  However in the variable.md these items are under a heading of Disclosure Policy, not Disclosure Terms.

Is my reading of this correct?  Should this be standardised on term/policy?

**Comment by dantrauner** [comment]
I think this is good to keep consistent since we refer to "Disclosure Policy" in other places – I made a change in my open PR to reflect this, especially since in that version, `Disclosure Policy` is called out with a special definition: https://github.com/disclose/disclose/pull/8/files#diff-a3d43eb061d7e3a0b80aef1305bfc8e9R7
